In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv("FinalOutput_orden.csv")

In [3]:
dataset

S.No          BP         AT        PM10         RH       PM2.5  \
0     564  740.000000  17.437083  711.552646  67.176667  519.594167   
1    1454  980.795417  31.779167   88.937500  55.280000   32.875000   
2     115  740.000000  37.692083  532.771567  21.725417  157.167083   
3    2161  972.096250  21.465000  179.125000  76.462917  153.677083   
4     145  740.000000  39.137083  560.061617  24.482917  162.872500   
..    ...         ...        ...         ...        ...         ...   
310   918  737.635757  24.789489  443.037470  44.005243  192.375085   
311  1002  737.635757  24.789489  443.037470  44.005243  192.375085   
312   882  737.635757  24.789489  443.037470  44.005243  192.375085   
313   989  737.635757  24.789489  443.037470  44.005243  192.375085   
314  1052  738.916389  22.966432  378.148840  42.099486  149.929831   

             WD        WS         NH3        CO          NO         NO2  \
0    237.725417  1.108333  148.204583  1.550000  210.351250   95.988750   
1     90.609583  1.463750   44.985000  0.772299   12.456250   44.293333   
2    206.365000  1.305417   31.337083  1.942500   11.281667   61.652917   
3    237.656250  0.352083    7.502500  2.066250   18.486667   17.593750   
4    253.540417  3.340833   36.914167  1.146548  155.567500  118.917083   
..          ...       ...         ...       ...         ...         ...   
310  206.168857  1.069558   80.539796  2.592207  104.938665  109.599813   
311  206.168857  1.069558   80.539796  2.592207  104.938665  109.599813   
312  206.168857  1.069558   80.539796  2.592207  104.938665  109.599813   
313  206.168857  1.069558   80.539796  2.592207  104.938665  109.599813   
314  198.983226  0.840631   66.526156  2.394345   62.962305  107.826998   

            NOx        SO2      Ozone  AQI Simulink       Label  
0    292.005563  14.662530  12.021250       4.285714    Healthy  
1     33.711250   9.143167  17.640833       4.421459    Healthy  
2     70.262917  19.507509  14.038946       4.049023    Healthy  
3     24.432083  19.746899  26.724583       4.390401    Healthy  
4    329.332083  10.107500  12.099167       4.285714    Healthy  
..          ...        ...        ...            ...        ...  
310  214.506152  29.056553  34.225155       6.785714  Unhealthy  
311  214.506152  29.056553  34.225155       6.785714  Unhealthy  
312  214.506152  29.056553  34.225155       6.785714  Unhealthy  
313  214.506152  29.056553  34.225155       6.785714  Unhealthy  
314  168.098236  37.007587  23.864029       6.604028  Unhealthy  

[315 rows x 17 columns]

In [4]:
dataset=dataset.drop("S.No",axis=1)

In [5]:
dataset.sort_values(["BP", "AT", "PM10", "RH", "PM2.5", "WD", "WS", "NH3", "CO", "NO", "NO2", "NOx", "SO2", "Ozone"], axis=0, inplace=True)

In [6]:
dataset

BP         AT        PM10         RH       PM2.5          WD  \
60   729.995417  32.477083   72.947917  60.560833   31.906250  120.875000   
88   730.395833  28.222083   60.333333  87.962500   41.906250  129.770833   
196  732.476250  23.513333  258.291667  50.041667   99.583333  225.177917   
158  732.590000  23.014583  270.250000  56.225000   89.500000  265.715833   
249  732.698333  26.498750  448.473946  46.759167  267.875000  108.924583   
..          ...        ...         ...        ...         ...         ...   
144  986.900000   8.392083  517.020833  82.520833  359.645833  180.479167   
114  986.900000   8.967917  459.802109  79.306667  367.375000  124.072917   
147  986.934167  21.777917  320.843750  69.022500  158.697917  250.333333   
100  988.429583  24.662083  208.500611  61.377083   50.593750   86.604167   
75   990.153447  12.357083  233.052083  60.833333  102.927083   87.062500   

           WS         NH3        CO          NO         NO2         NOx  \
60   1.105833   46.082500  1.438750   12.403333   22.256250   34.242083   
88   0.749167   54.284167  1.569167   10.211667   20.305833   30.514583   
196  1.109167   33.620417  1.324583   61.535417  115.243333   92.834583   
158  1.458750   35.750000  3.642083   87.548750  166.194583  152.442917   
249  0.930000  120.177917  4.377500   68.390638  136.909167  172.406890   
..        ...         ...       ...         ...         ...         ...   
144  0.362917   67.722956  2.871250   64.456766  140.551099  122.678332   
114  0.841250   58.131709  2.865384   72.449519   54.450000  108.924818   
147  0.482083   74.068750  2.239382  232.888333  101.411667  244.424583   
100  1.246250   54.503333  2.269944    3.352917   12.637500    9.390833   
75   3.348333   33.491667  1.425833    9.864167   36.382500   27.400833   

           SO2      Ozone  AQI Simulink       Label  
60    5.041250  14.698333       4.285714    Healthy  
88    3.565000  14.762917       4.320955    Healthy  
196  16.764167  22.070417       5.745257   Moderate  
158  14.460000  15.736667       4.821618   Moderate  
249  24.937917  59.214180       6.749453  Unhealthy  
..         ...        ...            ...        ...  
144  11.830417  65.546667       6.057403   Moderate  
114  10.653750  60.290833       6.468215   Moderate  
147   4.607083  37.186250       5.785714   Moderate  
100  13.752917  81.005147       4.499592    Healthy  
75    7.755417  15.044167       4.288199    Healthy  

[315 rows x 16 columns]

In [7]:
dataset.groupby(["Label"]).size()

Label
Healthy      105
Moderate     105
Unhealthy    105
dtype: int64

In [8]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
dataset["Label"]=label_encoder.fit_transform(dataset["Label"])
dataset["Label"].unique()

array([0, 1, 2])

In [9]:
indep = dataset[["BP", "AT","PM10","AT", "RH", "PM2.5", "WD", "WS", "NH3", "CO", "NO", "NO2", "NOx", "SO2", "Ozone",'AQI Simulink ']];
dep = dataset[["Label"]];

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# RandomForestClassifier

In [12]:
from sklearn.ensemble import RandomForestClassifier

In [13]:
from sklearn.model_selection import GridSearchCV
param_grid = {'criterion':['gini','entropy'],
              'max_features': ['auto','sqrt','log2'],
              'n_estimators':[10,100]} 
grid = GridSearchCV(RandomForestClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1') 
grid.fit(X_train, y_train) 

Fitting 5 folds for each of 12 candidates, totalling 60 fits


C:\Users\vijai\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:969: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan nan nan nan nan nan nan nan]
  warnings.warn(
C:\Users\vijai\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:926: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)


GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             scoring='f1', verbose=3)

In [14]:
re=grid.cv_results_
grid_predictions = grid.predict(X_test) 
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions) 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [15]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'gini', 'max_features': 'auto', 'n_estimators': 10}: 0.9714451090102256


In [16]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[35  3  0]
 [ 0 34  0]
 [ 0  0 33]]


In [17]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       1.00      0.92      0.96        38
           1       0.92      1.00      0.96        34
           2       1.00      1.00      1.00        33

    accuracy                           0.97       105
   macro avg       0.97      0.97      0.97       105
weighted avg       0.97      0.97      0.97       105



In [18]:
table=pd.DataFrame.from_dict(re)

In [19]:
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.123730      0.072148         0.087156        0.093767   
1        0.375305      0.047705         0.033606        0.005986   
2        0.042411      0.003202         0.012003        0.004383   
3        0.431317      0.058002         0.068818        0.029226   
4        0.047215      0.004667         0.016807        0.013718   
5        0.392906      0.034082         0.034411        0.001958   
6        0.048812      0.005878         0.012004        0.002527   
7        0.443319      0.031441         0.036011        0.002535   
8        0.047212      0.002994         0.009602        0.001959   
9        0.428114      0.022643         0.039205        0.006882   
10       0.048813      0.003920         0.011200        0.001598   
11       0.433718      0.036896         0.039210        0.004668   

   param_criterion param_max_features param_n_estimators  \
0             gini               auto                 10   
1             gini               auto                100   
2             gini               sqrt                 10   
3             gini               sqrt                100   
4             gini               log2                 10   
5             gini               log2                100   
6          entropy               auto                 10   
7          entropy               auto                100   
8          entropy               sqrt                 10   
9          entropy               sqrt                100   
10         entropy               log2                 10   
11         entropy               log2                100   

                                               params  split0_test_score  \
0   {'criterion': 'gini', 'max_features': 'auto', ...                NaN   
1   {'criterion': 'gini', 'max_features': 'auto', ...                NaN   
2   {'criterion': 'gini', 'max_features': 'sqrt', ...                NaN   
3   {'criterion': 'gini', 'max_features': 'sqrt', ...                NaN   
4   {'criterion': 'gini', 'max_features': 'log2', ...                NaN   
5   {'criterion': 'gini', 'max_features': 'log2', ...                NaN   
6   {'criterion': 'entropy', 'max_features': 'auto...                NaN   
7   {'criterion': 'entropy', 'max_features': 'auto...                NaN   
8   {'criterion': 'entropy', 'max_features': 'sqrt...                NaN   
9   {'criterion': 'entropy', 'max_features': 'sqrt...                NaN   
10  {'criterion': 'entropy', 'max_features': 'log2...                NaN   
11  {'criterion': 'entropy', 'max_features': 'log2...                NaN   

    split1_test_score  split2_test_score  split3_test_score  \
0                 NaN                NaN                NaN   
1                 NaN                NaN                NaN   
2                 NaN                NaN                NaN   
3                 NaN                NaN                NaN   
4                 NaN                NaN                NaN   
5                 NaN                NaN                NaN   
6                 NaN                NaN                NaN   
7                 NaN                NaN                NaN   
8                 NaN                NaN                NaN   
9                 NaN                NaN                NaN   
10                NaN                NaN                NaN   
11                NaN                NaN                NaN   

    split4_test_score  mean_test_score  std_test_score  rank_test_score  
0                 NaN              NaN             NaN                1  
1                 NaN              NaN             NaN                2  
2                 NaN              NaN             NaN                3  
3                 NaN              NaN             NaN                4  
4                 NaN              NaN             NaN                5  
5                 NaN              NaN             NaN                6  
6          