In [1]:
import numpy as np
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
pd.set_option('display.max_columns', None)

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn.metrics import accuracy_score

In [3]:
data = pd.read_csv("resumes_development.csv")

In [4]:
data

Unnamed: 0  Interview  Adobe Illustrator  Adobe Photoshop  \
0             0        1.0                0.0              0.0   
1             1        1.0                0.0              0.0   
2             2        0.0                0.0              0.0   
3             3        1.0                0.0              0.0   
4             4        1.0                0.0              0.0   
..          ...        ...                ...              ...   
614         619        0.0                0.0              0.0   
615         620        0.0                0.0              0.0   
616         621        1.0                0.0              0.0   
617         622        0.0                0.0              0.0   
618         623        1.0                0.0              0.0   

     Agile Methodologies  Analytical Skills  Art  Art Direction  Auditing  \
0                    1.0                0.0  0.0            0.0       0.0   
1                    0.0                0.0  0.0            0.0       0.0   
2                    0.0                0.0  0.0            0.0       0.0   
3                    0.0                0.0  0.0            0.0       0.0   
4                    0.0                0.0  0.0            0.0       0.0   
..                   ...                ...  ...            ...       ...   
614                  0.0                0.0  0.0            0.0       0.0   
615                  0.0                0.0  0.0            0.0       0.0   
616                  0.0                0.0  0.0            0.0       0.0   
617                  0.0                0.0  0.0            0.0       0.0   
618                  0.0                0.0  0.0            0.0       0.0   

     AutoCAD  Automation  Automotive  Baseball  Basketball  Branding  \
0        0.0         0.0         0.0       0.0         0.0       0.0   
1        0.0         0.0         0.0       1.0         0.0       0.0   
2        0.0         0.0         0.0       0.0         0.0       0.0   
3        0.0         0.0         0.0       0.0         0.0       0.0   
4        0.0         0.0         0.0       1.0         0.0       0.0   
..       ...         ...         ...       ...         ...       ...   
614      0.0         0.0         0.0       0.0         0.0       0.0   
615      0.0         0.0         0.0       1.0         0.0       0.0   
616      0.0         0.0         0.0       0.0         1.0       0.0   
617      0.0         0.0         0.0       0.0         0.0       0.0   
618      0.0         0.0         0.0       0.0         0.0       0.0   

     Budgeting  Business Analysis  Business Intelligence  Business Planning  \
0          0.0                0.0                    0.0                1.0   
1          1.0                0.0                    0.0                0.0   
2          0.0                0.0                    0.0                0.0   
3          0.0                0.0                    0.0                0.0   
4          0.0                0.0                    0.0                0.0   
..         ...                ...                    ...                ...   
614        1.0                0.0                    0.0                0.0   
615        0.0                0.0                    0.0                0.0   
616        0.0                0.0                    0.0                0.0   
617        0.0                0.0                    0.0                0.0   
618        0.0                0.0                    0.0                0.0   

     Business Process  Business Process Improvement  Business Services  \
0                 0.0                           0.0                0.0   
1                 0.0                           0.0                0.0   
2                 0.0                           0.0                0.0   
3                 0.0                           0.0                0.0   
4                 0.0                           0.0                0.0   
..                ...        

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 619 entries, 0 to 618
Columns: 224 entries, Unnamed: 0 to Disability
dtypes: float64(219), int64(5)
memory usage: 1.1 MB


In [6]:
data=data.drop("Unnamed: 0", axis=1)

In [7]:
data.groupby(["Interview"]).size()

Interview
0.0    400
1.0    219
dtype: int64

In [8]:
df_grouped_by = data.groupby(['Interview'])
df_balanced = df_grouped_by.apply(lambda x: x.sample(df_grouped_by.size().min()).reset_index(drop=True))
data = df_balanced.droplevel(['Interview'])

In [9]:
data.groupby(["Interview"]).size()

Interview
0.0    219
1.0    219
dtype: int64

In [10]:
df = data.copy()

In [11]:
X=data.drop("Interview",axis=1)
y=df["Interview"]

In [12]:
X

Adobe Illustrator  Adobe Photoshop  Agile Methodologies  \
0                  0.0              0.0                  0.0   
1                  0.0              0.0                  0.0   
2                  0.0              0.0                  0.0   
3                  0.0              0.0                  0.0   
4                  0.0              0.0                  0.0   
..                 ...              ...                  ...   
214                0.0              0.0                  1.0   
215                0.0              0.0                  1.0   
216                0.0              0.0                  1.0   
217                0.0              0.0                  1.0   
218                0.0              0.0                  0.0   

     Analytical Skills  Art  Art Direction  Auditing  AutoCAD  Automation  \
0                  0.0  0.0            0.0       0.0      0.0         0.0   
1                  0.0  0.0            0.0       0.0      0.0         0.0   
2                  0.0  0.0            0.0       0.0      0.0         0.0   
3                  0.0  0.0            0.0       0.0      0.0         0.0   
4                  0.0  0.0            0.0       0.0      0.0         0.0   
..                 ...  ...            ...       ...      ...         ...   
214                0.0  0.0            0.0       0.0      0.0         0.0   
215                0.0  0.0            0.0       0.0      0.0         0.0   
216                0.0  0.0            0.0       0.0      0.0         0.0   
217                0.0  0.0            0.0       0.0      0.0         0.0   
218                0.0  0.0            0.0       0.0      0.0         0.0   

     Automotive  Baseball  Basketball  Branding  Budgeting  Business Analysis  \
0           0.0       0.0         0.0       0.0        0.0                0.0   
1           0.0       0.0         0.0       0.0        0.0                0.0   
2           1.0       0.0         0.0       0.0        0.0                0.0   
3           0.0       0.0         0.0       0.0        0.0                0.0   
4           0.0       0.0         0.0       0.0        0.0                0.0   
..          ...       ...         ...       ...        ...                ...   
214         0.0       0.0         1.0       0.0        0.0                0.0   
215         0.0       0.0         0.0       0.0        0.0                0.0   
216         0.0       0.0         0.0       0.0        0.0                0.0   
217         0.0       0.0         0.0       0.0        0.0                0.0   
218         0.0       0.0         0.0       0.0        1.0                0.0   

     Business Intelligence  Business Planning  Business Process  \
0                      0.0                0.0               0.0   
1                      0.0                0.0               0.0   
2                      0.0                0.0               0.0   
3                      0.0                0.0               0.0   
4                      0.0                0.0               0.0   
..                     ...                ...               ...   
214                    0.0                0.0               0.0   
215                    0.0                0.0               0.0   
216                    0.0                0.0               0.0   
217                    0.0                0.0               0.0   
218                    0.0                0.0               0.0   

     Business Process Improvement  Business Services  Business Strategy  \
0                             0.0                0.0                0.0   
1                             0.0                0.0                0.0   
2                             0.0                0.0                0.0   
3                             0.0                0.0                0.0   
4                             0.0                0.0                1.0   
..                            ...                ...                ...   
214     

In [13]:
y

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ... 
214    1.0
215    1.0
216    1.0
217    1.0
218    1.0
Name: Interview, Length: 438, dtype: float64

In [14]:
#X = pd.DataFrame(data = data.data, columns=data.feature_names)

In [15]:
#y=data.target

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 0)
X_train.shape, X_test.shape

((350, 222), (88, 222))

In [17]:
sel = SelectFromModel(RandomForestClassifier(n_estimators=100, random_state=0, n_jobs=-1))
sel.fit(X_train, y_train)
sel.get_support()

array([False, False,  True, False, False, False, False,  True, False,
       False,  True,  True, False,  True, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False,  True,  True, False,  True,  True,  True,  True, False,
       False,  True, False,  True,  True, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False,  True, False, False,  True, False, False,
        True,  True, False, False, False, False, False, False,  True,
       False,  True, False, False, False, False, False, False,  True,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False,  True,  True, False,  True, False, False, False, False,
       False, False,

In [18]:
X_train.columns

Index(['Adobe Illustrator', 'Adobe Photoshop', 'Agile Methodologies',
       'Analytical Skills', 'Art', 'Art Direction', 'Auditing', 'AutoCAD',
       'Automation', 'Automotive',
       ...
       'Windows', 'Windows Server', 'Wireless Technologies', 'WordPress',
       'Workshops', 'Writing', 'Veteran', 'Female', 'URM', 'Disability'],
      dtype='object', length=222)

In [19]:
features = X_train.columns[sel.get_support()]

In [20]:
features

Index(['Agile Methodologies', 'AutoCAD', 'Baseball', 'Basketball', 'Budgeting',
       'Coaching', 'Customer Relationship Management', 'Customer Satisfaction',
       'Data Analysis', 'Databases', 'Decision Making',
       'Department of Defense', 'Digital Marketing', 'Diving', 'Drawing',
       'Energy', 'Football', 'Gas', 'Government Agencies', 'Grant Writing',
       'Healthcare', 'Heavy Equipment', 'Information Technology',
       'Interpersonal Skills', 'Logistics Management', 'Military Aviation',
       'Military Weapons', 'Network Administration', 'Nonprofit Organizations',
       'Operations Management', 'Oracle Database', 'Performance Tuning',
       'Presentations', 'Public Policy', 'Qualifying Prospects',
       'Sales Management', 'Soccer', 'Swimming', 'Unix', 'Video Production',
       'Volunteering', 'Web Development', 'Wireless Technologies', 'WordPress',
       'Veteran', 'Female', 'URM', 'Disability'],
      dtype='object')

In [21]:
len(features)

48

In [22]:
X_train_rfc = sel.transform(X_train)
X_test_rfc = sel.transform(X_test)

In [23]:
np.mean(sel.estimator_.feature_importances_)

0.0045045045045045045

In [24]:
sel.estimator_.feature_importances_

array([3.27543701e-03, 3.62942574e-03, 1.16581295e-02, 1.10865431e-03,
       1.03144552e-04, 4.25359705e-03, 9.21555126e-04, 6.71340456e-03,
       1.02540094e-03, 2.33886487e-03, 3.20562108e-02, 1.12589668e-02,
       1.61535254e-03, 7.17613210e-03, 2.82443365e-04, 5.50615855e-04,
       1.08020624e-03, 4.03228169e-03, 2.28288318e-03, 1.78449576e-03,
       1.86228580e-03, 1.26084910e-03, 6.24991147e-03, 1.54019344e-04,
       4.89577548e-04, 1.45335493e-03, 7.15122982e-04, 6.71160749e-04,
       7.72049396e-03, 7.08802321e-03, 3.86464168e-03, 7.69925018e-03,
       8.99440586e-03, 8.25577797e-03, 7.44031107e-03, 2.65514137e-03,
       1.05863766e-04, 1.08051180e-02, 1.14320139e-03, 7.33489979e-03,
       4.64681574e-03, 1.41246769e-03, 2.92271383e-03, 2.14310849e-03,
       7.88402475e-04, 3.39428329e-03, 5.05619768e-03, 1.74013507e-03,
       1.21225892e-03, 0.00000000e+00, 1.20769690e-03, 3.93442390e-03,
       5.34876319e-04, 2.44814107e-03, 4.64541421e-04, 3.77813298e-03,
      

In [25]:
def run_randomForest(X_train, X_test, y_train, y_test):
    clf = RandomForestClassifier(n_estimators=100, random_state=0, n_jobs=-1)
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    print('Accuracy: ', accuracy_score(y_test,y_pred))

In [26]:
%%time
run_randomForest(X_train_rfc, X_test_rfc, y_train, y_test)

Accuracy:  0.9204545454545454
Wall time: 396 ms


In [27]:
%%time
run_randomForest(X_train, X_test, y_train, y_test)

Accuracy:  0.8863636363636364
Wall time: 462 ms


# Recursive Feature Elimination (RFE)

In [28]:
from sklearn.feature_selection import RFE
sel = RFE(RandomForestClassifier(n_estimators=100, random_state=0, n_jobs=-1), n_features_to_select = 15)
sel.fit(X_train, y_train)

RFE(estimator=RandomForestClassifier(n_jobs=-1, random_state=0),
    n_features_to_select=15)

In [29]:
sel.get_support()

array([False, False,  True, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False,  True, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False,  True, False, False,  True, False, False, False, False,
       False, False,

In [30]:
features = X_train.columns[sel.get_support()]

In [31]:
features

Index(['Agile Methodologies', 'Baseball', 'Data Analysis',
       'Department of Defense', 'Digital Marketing', 'Football', 'Healthcare',
       'Logistics Management', 'Military Aviation', 'Network Administration',
       'Oracle Database', 'Swimming', 'Veteran', 'Female', 'Disability'],
      dtype='object')

In [32]:
len(features)

15

In [33]:
X_train_rfe = sel.transform(X_train)
X_test_rfe = sel.transform(X_test)

In [34]:
%%time
run_randomForest(X_train_rfe, X_test_rfe, y_train, y_test)

Accuracy:  0.875
Wall time: 389 ms


In [35]:
%%time
run_randomForest(X_train, X_test, y_train, y_test)

Accuracy:  0.8863636363636364
Wall time: 410 ms


In [36]:
from sklearn.ensemble import AdaBoostClassifier
sel = RFE(AdaBoostClassifier(n_estimators=100, random_state=0), n_features_to_select = 15)
sel.fit(X_train, y_train)

RFE(estimator=AdaBoostClassifier(n_estimators=100, random_state=0),
    n_features_to_select=15)

In [37]:
sel.get_support()

array([False, False, False, False, False, False, False, False, False,
       False,  True, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False,  True, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [38]:
features = X_train.columns[sel.get_support()]

In [39]:
features

Index(['Baseball', 'Budgeting', 'Data Analysis', 'Decision Making',
       'Digital Marketing', 'Government Agencies', 'Information Technology',
       'Pricing Strategy', 'Soccer', 'Swimming', 'Team Management',
       'Volunteering', 'Wireless Technologies', 'Veteran', 'Female'],
      dtype='object')

In [40]:
len(features)

15

In [41]:
X_train_rfe = sel.transform(X_train)
X_test_rfe = sel.transform(X_test)

In [42]:
%%time
run_randomForest(X_train_rfe, X_test_rfe, y_train, y_test)

Accuracy:  0.8181818181818182
Wall time: 375 ms


In [43]:
%%time
run_randomForest(X_train, X_test, y_train, y_test)

Accuracy:  0.8863636363636364
Wall time: 418 ms


In [44]:
for index in range(1,11):
    from sklearn.ensemble import RandomForestClassifier
    sel = RFE(RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0), n_features_to_select = index)
    sel.fit(X_train, y_train)
    X_train_rfe = sel.transform(X_train)
    X_test_rfe = sel.transform(X_test)
    features = X_train.columns[sel.get_support()]
    print('Selected Feature: ',index,features)
    run_randomForest(X_train_rfe, X_test_rfe, y_train, y_test)
    print()

Selected Feature:  1 Index(['Veteran'], dtype='object')
Accuracy:  0.8636363636363636

Selected Feature:  2 Index(['Oracle Database', 'Veteran'], dtype='object')
Accuracy:  0.8636363636363636

Selected Feature:  3 Index(['Baseball', 'Oracle Database', 'Veteran'], dtype='object')
Accuracy:  0.8636363636363636

Selected Feature:  4 Index(['Baseball', 'Oracle Database', 'Veteran', 'Female'], dtype='object')
Accuracy:  0.875

Selected Feature:  5 Index(['Baseball', 'Digital Marketing', 'Oracle Database', 'Veteran',
       'Female'],
      dtype='object')
Accuracy:  0.8636363636363636

Selected Feature:  6 Index(['Baseball', 'Digital Marketing', 'Football', 'Oracle Database',
       'Veteran', 'Female'],
      dtype='object')
Accuracy:  0.8636363636363636

Selected Feature:  7 Index(['Agile Methodologies', 'Baseball', 'Digital Marketing', 'Football',
       'Oracle Database', 'Veteran', 'Female'],
      dtype='object')
Accuracy:  0.7954545454545454

Selected Feature:  8 Index(['Agile Method